### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by k33g** [CleverCloud/clever-tools#113]
Hey 👋  @waxzce @Keruspe  when I try to deploy my application with:

```shell
clever deploy --alias demo_app01 --verbose true
```

I get an error:

```shell
/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1164
    throw error;
    ^

TypeError: Cannot read property 'replace' of null
    at Object.Git.createRemote (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/src/models/git.js:92:24)
    at /Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/src/commands/deploy.js:28:16
    at /Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:2465:27
    at spawn (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:2056:34)
    at Object.sink (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:2105:20)
    at Dispatcher.pushToSubscriptions (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1155:23)
    at Dispatcher.pushIt (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1177:10)
    at Object.Bacon.UpdateBarrier.inTransaction (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:356:16)
    at Dispatcher.push (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1146:24)
    at Dispatcher.handleEvent (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1199:17)
    at /Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:232:17
    at Object.sink (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1672:16)
    at Dispatcher.pushToSubscriptions (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1155:23)
    at Dispatcher.pushIt (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1177:10)
    at Object.Bacon.UpdateBarrier.inTransaction (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:356:16)
    at Dispatcher.push (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1146:24)
    at Dispatcher.extend.push (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1587:38)
    at Dispatcher.handleEvent (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1199:17)
    at /Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:232:17
    at Object.sink (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1295:20)
    at Dispatcher.pushToSubscriptions (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1155:23)
    at Dispatcher.pushIt (/Users/k33g/.nvm/versions/node/v6.4.0/lib/node_modules/clever-tools/node_modules/baconjs/dist/Bacon.js:1177:10)
```

Can you help me? 🙏

**Comment by k33g** [comment]
Perhaps, I misunderstood deploy signification, because with a `restart` I have what I want

**Comment by Keruspe** [comment]
Should be fixed if you unlink and link again, thanks!
