### ISSUE TITLE
Package standalone app with zeit/pkg

### ISSUE THREAD

**Issue by waxzce** [CleverCloud/clever-tools#127]
https://www.npmjs.com/package/pkg

Wanna try it?

**Comment by divarvel** [comment]
Would replace #45 and #46

**Comment by divarvel** [comment]
I've started working on it, in the pkg branch.
~everything works ok, except… [drumroll] *nodegit*

**Comment by divarvel** [comment]
So, having the compiled the app with `pkg .` and put the resulting binary (as well as `nodegit.node`) somewhere in `$PATH`, here's what I get:

```
$  clever-tools-macos deploy
[ERROR] Error: Callback is required and must be a Function.
    at Error (native)
    at /snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/nodegit-promise/lib/node-extensions.js:24:20
    at tryCallTwo (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/nodegit-promise/lib/core.js:45:5)
    at doResolve (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/nodegit-promise/lib/core.js:173:13)
    at new Promise (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/nodegit-promise/lib/core.js:65:3)
    at Remote.fetch (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/nodegit-promise/lib/node-extensions.js:19:12)
    at /snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/src/models/git.js:142:18
    at /snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:2465:27
    at spawn (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:2056:34)
    at Object.sink (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:2105:20)
    at Dispatcher.pushToSubscriptions (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:1155:23)
    at Dispatcher.pushIt (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:1177:10)
    at Object.inTransaction (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:356:16)
    at Dispatcher.push (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:1146:24)
    at Dispatcher._handleEvent (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:2679:19)
    at Dispatcher.handleEvent (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:1197:17)
    at Object.sink (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:232:17)
    at Dispatcher.pushToSubscriptions (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:1155:23)
    at Dispatcher.pushIt (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:1177:10)
    at Object.inTransaction (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:356:16)
    at Dispatcher.push (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:1146:24)
    at Dispatcher.handleEvent (/snapshot/Users/clementd/Projects/work/clever-cloud/clever-tools/node_modules/baconjs/dist/Bacon.js:1199:17)```

**Comment by divarvel** [comment]
After a pkg update, it works well. A homebrew formula is working, I'll publish archives for the next versions
