### ISSUE TITLE
clever login: Error: Cannot find module 'opn' on 1.5.0-beta.6

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#337]
With the last beta (1.5.0-beta6), when executing `clever login`:
```
~ $ clever login
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

Error: Cannot find module 'opn'
Require stack:
- /snapshot/clever-tools_1.5.0-beta.6/src/commands/login.js
- /snapshot/clever-tools_1.5.0-beta.6/bin/clever.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:608:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:524:27)
    at Module.require (internal/modules/cjs/loader.js:664:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/snapshot/clever-tools_1.5.0-beta.6/src/commands/login.js:9:13)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:768:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at Function.Module._load (internal/modules/cjs/loader.js:553:12)
    at Module.require (internal/modules/cjs/loader.js:664:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.action (/snapshot/clever-tools_1.5.0-beta.6/bin/clever.js:63:22)
    at Object.execute (/snapshot/clever-tools_1.5.0-beta.6/node_modules/cliparse/src/cli.js:88:30)
```

I had to downgrade to 1.4.2 to get it working.

**Comment by hsablonniere** [comment]
Fixed in latest beta
