### ISSUE TITLE
TypeError: Cannot read property 'constructor' of null when requesting add-ons of an organisation

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#338]
```
~ $ clever addon -o <orga_id>
(node:30859) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'constructor' of null
    at /snapshot/clever-tools_1.5.0-beta.6/node_modules/colors/lib/colors.js:108:34
    at Array.map (<anonymous>)
    at Function.applyStyle (/snapshot/clever-tools_1.5.0-beta.6/node_modules/colors/lib/colors.js:107:18)
    at Function.builder (/snapshot/clever-tools_1.5.0-beta.6/node_modules/colors/lib/colors.js:78:23)
    at /snapshot/clever-tools_1.5.0-beta.6/src/commands/addon.js:23:23
    at Array.map (<anonymous>)
    at /snapshot/clever-tools_1.5.0-beta.6/src/commands/addon.js:19:38
    at Next.valueF (/snapshot/clever-tools_1.5.0-beta.6/node_modules/baconjs/dist/Bacon.js:912:14)
    at Next.value (/snapshot/clever-tools_1.5.0-beta.6/node_modules/baconjs/dist/Bacon.js:901:31)
    at /snapshot/clever-tools_1.5.0-beta.6/node_modules/baconjs/dist/Bacon.js:1048:24
    at /snapshot/clever-tools_1.5.0-beta.6/node_modules/baconjs/dist/Bacon.js:463:23
    at processAfters (/snapshot/clever-tools_1.5.0-beta.6/node_modules/baconjs/dist/Bacon.js:359:11)
    at Object.inTransaction (/snapshot/clever-tools_1.5.0-beta.6/node_modules/baconjs/dist/Bacon.js:439:9)
    at Dispatcher.push (/snapshot/clever-tools_1.5.0-beta.6/node_modules/baconjs/dist/Bacon.js:1214:24)
    at Dispatcher.handleEvent (/snapshot/clever-tools_1.5.0-beta.6/node_modules/baconjs/dist/Bacon.js:1267:17)
    at /snapshot/clever-tools_1.5.0-beta.6/node_modules/baconjs/dist/Bacon.js:242:17
(node:30859) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30859) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Using the laste beta version. Works fine for user's add-on (without the `-o` flag)

**Comment by hsablonniere** [comment]
Only cause by postgresql_postgres_e7562d7d-2d9f-4ecf-b080-ade753b360c0
