### ISSUE TITLE
Handle cases where JSON body is invalid

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#352]
When JSON response body is invalid, we get this:

(this must be fixed in clever client)

```
TypeError: Cannot read property 'status' of undefined
at getErrorMessage (/usr/local/lib/node_modules/clever-tools/node_modules/@clevercloud/client/cjs/request.superagent.js:33:44)
at set.query.send.then.catch.error (/usr/local/lib/node_modules/clever-tools/node_modules/@clevercloud/client/cjs/request.superagent.js:40:21)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by justfortherec** [comment]
I also see this:

```
$ clever profile --verbose
[DEBUG] Load configuration from environment variables
[DEBUG] Load configuration from /home/user/.config/clever-cloud
[DEBUG] Load configuration from environment variables
[DEBUG] Load configuration from /home/user/.config/clever-cloud
[STACKTRACE]
TypeError: Cannot read property 'status' of undefined
    at getErrorMessage (/snapshot/clever-tools_1.6.2/node_modules/@clevercloud/client/cjs/request.superagent.js:33:44)
    at /snapshot/clever-tools_1.6.2/node_modules/@clevercloud/client/cjs/request.superagent.js:40:21
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Object.profile (/snapshot/clever-tools_1.6.2/src/commands/profile.js:9:45)
[/STACKTRACE]
[ERROR] Cannot read property 'status' of undefined
```
It seems as if any command that communicates with the server fails. 
Is there a workaround that I can apply?

**Comment by clementd-fretlink** [comment]
I've just experienced it in `clever activity` as well

**Comment by hsablonniere** [comment]
I will merge and release #365 in 10 days...

**Comment by hsablonniere** [comment]
It's merged and released. The pb may appear again but the error will be handled.
