### ISSUE TITLE
[BUG] [ERROR] Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by pYassine** [CleverCloud/clever-tools#572]
For 15 days, we have been facing a problem with the CLI.
When trying to deploy an app, the following message is displayed:

The CLI is installed via NPM.

      ```
[DEBUG] Loading app configuration from
     /Users/xxx/Documents/dev/XXXX/.clever.json [DEBUG] Load
     configuration from environment variables [DEBUG] Load configuration
     from /Users/XXXX/.config/clever-cloud/clever-tools.json [DEBUG] Get
     information for the app: app_bffa0b15-0e0f-49b4-b20b-0e31cef05b23
     [DEBUG] Load configuration from environment variables [DEBUG] Load
     configuration from
     /Users/XXXX/.config/clever-cloud/clever-tools.json [DEBUG] GET
     https://api.clever-cloud.com/v2/organisations/orga_XXXX/applications/app_XXXX
     ? undefined Remote git head commit   is
     e51944c92e80325fb5d8461f977b134f8e9d729f Current deployed commit  is
     e51944c92e80325fb5d8461f977b134f8e9d729f New local commit to push is
     5beaeaba81e10c2922625d82dfe5bd4e6bb5657d (from
     refs/heads/fix-ci-deploy) [DEBUG] Load configuration from environment
     variables [DEBUG] Load configuration from
     /Users/XXXX/.config/clever-cloud/clever-tools.json [DEBUG] GET
     https://api.clever-cloud.com/v2/organisations/orga_XXXX/applications/app_XXXX/deployments
     ? {"limit":5} Pushing source code to Clever Cloud… [DEBUG] Load
     configuration from environment variables [DEBUG] Load configuration
     from /Users/XXXX/.config/clever-cloud/clever-tools.json [STACKTRACE]
     TypeError: Cannot read property 'slice' of null
         at GitPackIndex.readSlice (/snapshot/clever-tools_2.10.1/node_modules/isomorphic-git/index.cjs:2791:35)
         at async readObjectPacked (/snapshot/clever-tools_2.10.1/node_modules/isomorphic-git/index.cjs:2908:22)
         at async _readObject (/snapshot/clever-tools_2.10.1/node_modules/isomorphic-git/index.cjs:2950:14)
         at async walk (/snapshot/clever-tools_2.10.1/node_modules/isomorphic-git/index.cjs:10998:30)
         at async walk (/snapshot/clever-tools_2.10.1/node_modules/isomorphic-git/index.cjs:11017:11)
         at async walk (/snapshot/clever-tools_2.10.1/node_modules/isomorphic-git/index.cjs:11017:11)
         at async walk (/snapshot/clever-tools_2.10.1/node_modules/isomorphic-git/index.cjs:11006:7)
         at async listObjects (/snapshot/clever-tools_2.10.1/node_modules/isomorphic-git/index.cjs:11024:5)
         at async _push (/snapshot/clever-tools_2.10.1/node_modules/isomorphic-git/index.cjs:11221:23)
         at async Object.push (/snapshot/clever-tools_2.10.1/node_modules/isomorphic-git/index.cjs:11431:12)
         at async Object.push (/snapshot/clever-tools_2.10.1/src/models/git.js:87:18)
         at async Object.deploy (/snapshot/clever-tools_2.10.1/src/commands/deploy.js:52:3) {  
     caller: 'git.push' } [/STACKTRACE]
```

**Comment by hsablonniere** [comment]
Hello @pYassine, can you contact our support team through our ticket center (in the web console)?

**Comment by pYassine** [comment]
@hsablonniere done !
