### ISSUE TITLE
clever curl: print error + help when no params

### ISSUE THREAD

**Issue by davlgd** [CleverCloud/clever-tools#617]
If a user launches `clever curl` without any url, such an error is printed : 

```
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at Url.parse (node:url:170:3)
    at Object.urlParse [as parse] (node:url:141:13)
    at parseCurlCommand (/usr/local/lib/node_modules/clever-tools/node_modules/curlconverter/util.js:141:25)
    at Object.curl (/usr/local/lib/node_modules/clever-tools/src/commands/curl.js:26:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/clever-tools/bin/clever.js:1096:38)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v21.1.0
```

We could use default URL, like `https://api.clever-cloud.com/v2/organisations`

If not, we should print a better error message.

**Comment by hsablonniere** [comment]
We won't add a default URL but we will improve the error + help display for:

* `clever curl` without anything else
* `clever curl -h`
* `clever curl --help`

**Comment by davlgd** [comment]
I checked in the code, and it seems that when `clever curl --help` is launched, the `curlconverter` package is called with a string `'curl' --help`, then the `yarg` parser is called, and in its `locale` folder we can find : 

<img width="1109" alt="image" src="https://github.com/CleverCloud/clever-tools/assets/1110600/cc5716f1-fb14-4a7f-916e-f29e5371da2b">

Maybe we should detect the `--help` argument at first and then show our own help message
