### ISSUE TITLE
3.5.0 - clever curl is broken on ubuntu

### ISSUE THREAD

**Issue by chmuche** [CleverCloud/clever-tools#713]
When I run this command since v3.5.0 

```sh
$ clever curl https://api.clever-cloud.com/v2/self
```

I got this error
```
/snapshot/clever-tools/src/commands/curl.js:80
  const curlParser = await import('curlconverter/dist/src/parse.js');
                     ^

TypeError: Invalid host defined options
    at parseCurlCommand (/snapshot/clever-tools/src/commands/curl.js:80:22)
    at Object.curl (/snapshot/clever-tools/src/commands/curl.js:51:31)
    at Object.<anonymous> (/snapshot/clever-tools/bin/clever.js:1130:38)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.15.0
```

clever-tools is installed with `https://nexus.clever-cloud.com/repository/deb`

Maybe I missed something

**Comment by davlgd** [comment]
Can you paste `clever diag` info ? We'll check this asap 🙏

**Comment by chmuche** [comment]
```
clever-tools  3.5.0
Node.js       v18.15.0
Platform      linux
Release       6.6.10-76060610-generic
Architecture  x64
Linux         Pop!_OS 22.04 LTS
Shell         /usr/bin/zsh
Packaged      true
Exec path     /usr/bin/clever
Config file   /home/apasquier/.config/clever-cloud/clever-tools.json
Auth source   configuration file
oAuth token   xxxxxxxxxxxxxxxxxxx
User ID       user_xxxxxxxxxxxxxxx
```

**Comment by davlgd** [comment]
Thanks I'll check with a Pop!_OS later today and let you know

**Comment by davlgd** [comment]
I've reproduced it on a similar system. Team is looking for a fix.

**Comment by draescherl** [comment]
Reproduced on Fedora 39

**Comment by hsablonniere** [comment]
Hello everyone, we're very sorry for this one. I have a fix, we're going through the test and release in the next hours...
